namespace Burile.Financial.AlphaVantage.Enums;

internal enum ApiFunction
{
    TIME_SERIES_INTRADAY,
    TIME_SERIES_INTRADAY_EXTENDED,
    TIME_SERIES_DAILY,
    TIME_SERIES_DAILY_ADJUSTED,
    TIME_SERIES_WEEKLY,
    TIME_SERIES_WEEKLY_ADJUSTED,
    TIME_SERIES_MONTHLY,
    TIME_SERIES_MONTHLY_ADJUSTED,
}